### ISSUE TITLE
[FIXED] Game Hangs When Underground

### ISSUE THREAD

**Issue by TimeBender25** [LiviiYS/Euphoric_Curiosity#63] opened 2022-02-24 09:17 UTC
As the title says, the game will hang randomly while in the caves. I've had it happen as high up as y37, which makes half the game kind of difficult to access.

To note, it does not *crash*. It only *hangs*  and freezes and I have to force close the game (With ALT+F4, as my cursor is captured and ALT TAB does not recover it). Here are the [latest](https://gist.github.com/TimeBender25/84dd516314d008b174b182e13c29dbf7) and [rei](https://gist.github.com/TimeBender25/6acdda52f95cedbb9039245032e7af85) logs, 'cause I'm fuck out of the clues I never had to start with.

I really hope to enjoy this pack, I don't know what's happening to spoil the fun.

**Comment by Schockolade** [comment] 2022-02-24 12:08
I have the same problem. Started to play some days ago with this modpack but now it crashes shortly after loading my world. I tried to update all the mods to the newest version but it did not help.
[rei.log](https://github.com/LiviiYS/Euphoric_Curiosity/files/8132311/rei.log)
[latest.log](https://github.com/LiviiYS/Euphoric_Curiosity/files/8132312/latest.log)

**Comment by LiviiYS** [comment] 2022-02-24 12:42
Should be fixed on 1.4.1

**Comment by Schockolade** [comment] 2022-02-25 11:33
Just tried the 1.14.1 Version of the pack. The problem is the same. It crashes or freezes at the same spots. Can I provide other logs or test something to help to figure it out? 
[rei.log](https://github.com/LiviiYS/Euphoric_Curiosity/files/8140766/rei.log)
[latest.log](https://github.com/LiviiYS/Euphoric_Curiosity/files/8140767/latest.log)

**Comment by LiviiYS** [comment] 2022-02-25 11:37
Could i also get the crash report?
if it has one

**Comment by Schockolade** [comment] 2022-02-25 11:57
Sorry, I cant find any crash report for this

**Comment by LiviiYS** [comment] 2022-02-25 12:07
That's alright, working with mod dev to work this out.

Thanks for reporting the issue

**Comment by RandAlThorn** [comment] 2022-02-28 18:19
i can report the same issue. No crash reports just freezes the screen and have to close the game and either relog and hope i have time to move away or teleport myself somewhere else through server console.

**Comment by North-West-Wind** [comment] 2022-03-01 07:34
I suspect the error is not the main cause. My game plays completely normal until a few hours ago. I came across this issue and it seems everyone's log has the line `java.lang.NullPointerException: Cannot invoke "dev.emi.trinkets.TrinketScreen.trinkets$updateTrinketSlots()" because "dev.emi.trinkets.TrinketScreenManager.currentScreen" is null` as said by @RandAlThorn 

Therefore, I went to [Trinkets' repo](https://github.com/emilyploszaj/trinkets) and someone also reported the [similar issue](https://github.com/emilyploszaj/trinkets/issues/152). The author seems to have patched it on GitHub:
> Not exactly sure what would be causing that truthfully, this method should not be called very frequently. Either way, it's been fixed in the main branch, I'll close this issue the next release I make.

So I tried compiling the mod from GitHub and the game still freezes, which makes me think the said error might not be the cause.
[Here's my latest.log](https://pastebin.com/PAqayjBz) if you care.

**Comment by LiviiYS** [comment] 2022-03-01 08:02
> I suspect the error is not the main cause. My game plays completely normal until a few hours ago. I came across this issue and it seems everyone's log has the line `java.lang.NullPointerException: Cannot invoke "dev.emi.trinkets.TrinketScreen.trinkets$updateTrinketSlots()" because "dev.emi.trinkets.TrinketScreenManager.currentScreen" is null` as said by @RandAlThorn 
> 
> Therefore, I went to [Trinkets' repo](https://github.com/emilyploszaj/trinkets) and someone also reported the [similar issue](https://github.com/emilyploszaj/trinkets/issues/152). The author seems to have patched it on GitHub:
> > Not exactly sure what would be causing that truthfully, this method should not be called very frequently. Either way, it's been fixed in the main branch, I'll close this issue the next release I make.
> 
> So I tried compiling the mod from GitHub and the game still freezes, which makes me think the said error might not be the cause.
> [Here's my latest.log](https://pastebin.com/PAqayjBz) if you care.


Just looked at the log & it references kubejs loot tables.

Also I was the one to report to the trinket GitHub

**Comment by TimeBender25** [comment] 2022-03-01 08:06
I'm not going to pretend to know the black magic of loot tables, but wouldn't that only be called when something drops? It's certainly locked up in other situations before.

**Comment by xanthian** [comment] 2022-03-02 09:22
Welcome to yesterday :P
![image](https://user-images.githubusercontent.com/7688001/156332845-11633353-8fda-4fae-a3fd-97347ed1a672.png)

**Closed** 2022-03-12 07:38 UTC
